package cn.clothes.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="documentary_flow")
public class DocumentaryFlow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentary_flow.id
     *
     * @mbg.generated Fri Apr 13 12:31:27 CST 2018
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documentary_flow.flow
     *
     * @mbg.generated Fri Apr 13 12:31:27 CST 2018
     */
    private String flow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_flow.id
     *
     * @return the value of documentary_flow.id
     *
     * @mbg.generated Fri Apr 13 12:31:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_flow.id
     *
     * @param id the value for documentary_flow.id
     *
     * @mbg.generated Fri Apr 13 12:31:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_flow.flow
     *
     * @return the value of documentary_flow.flow
     *
     * @mbg.generated Fri Apr 13 12:31:27 CST 2018
     */
    public String getFlow() {
        return flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_flow.flow
     *
     * @param flow the value for documentary_flow.flow
     *
     * @mbg.generated Fri Apr 13 12:31:27 CST 2018
     */
    public void setFlow(String flow) {
        this.flow = flow;
    }
}