package cn.clothes.domain;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
@Entity
@Table(name="financial_management_account_payable")
public class FinancialManagementAccountPayable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_account_payable.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_account_payable.financialManagementAccountPayableID
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer financialmanagementaccountpayableid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_account_payable.OrderID
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_account_payable.orderDate
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Date orderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_account_payable.billType
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String billtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_account_payable.client
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String client;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_account_payable.shipmentTrackingNumber
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer shipmenttrackingnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_account_payable.receivableAmount
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double receivableamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_account_payable.discountAmount
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double discountamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_account_payable.actualAmount
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double actualamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_account_payable.id
     *
     * @return the value of financial_management_account_payable.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Id
	@GeneratedValue
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_account_payable.id
     *
     * @param id the value for financial_management_account_payable.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_account_payable.financialManagementAccountPayableID
     *
     * @return the value of financial_management_account_payable.financialManagementAccountPayableID
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Integer getFinancialmanagementaccountpayableid() {
        return financialmanagementaccountpayableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_account_payable.financialManagementAccountPayableID
     *
     * @param financialmanagementaccountpayableid the value for financial_management_account_payable.financialManagementAccountPayableID
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setFinancialmanagementaccountpayableid(Integer financialmanagementaccountpayableid) {
        this.financialmanagementaccountpayableid = financialmanagementaccountpayableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_account_payable.OrderID
     *
     * @return the value of financial_management_account_payable.OrderID
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_account_payable.OrderID
     *
     * @param orderid the value for financial_management_account_payable.OrderID
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_account_payable.orderDate
     *
     * @return the value of financial_management_account_payable.orderDate
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Temporal(TemporalType.DATE)
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_account_payable.orderDate
     *
     * @param orderdate the value for financial_management_account_payable.orderDate
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_account_payable.billType
     *
     * @return the value of financial_management_account_payable.billType
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getBilltype() {
        return billtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_account_payable.billType
     *
     * @param billtype the value for financial_management_account_payable.billType
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setBilltype(String billtype) {
        this.billtype = billtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_account_payable.client
     *
     * @return the value of financial_management_account_payable.client
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getClient() {
        return client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_account_payable.client
     *
     * @param client the value for financial_management_account_payable.client
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setClient(String client) {
        this.client = client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_account_payable.shipmentTrackingNumber
     *
     * @return the value of financial_management_account_payable.shipmentTrackingNumber
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Integer getShipmenttrackingnumber() {
        return shipmenttrackingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_account_payable.shipmentTrackingNumber
     *
     * @param shipmenttrackingnumber the value for financial_management_account_payable.shipmentTrackingNumber
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setShipmenttrackingnumber(Integer shipmenttrackingnumber) {
        this.shipmenttrackingnumber = shipmenttrackingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_account_payable.receivableAmount
     *
     * @return the value of financial_management_account_payable.receivableAmount
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getReceivableamount() {
        return receivableamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_account_payable.receivableAmount
     *
     * @param receivableamount the value for financial_management_account_payable.receivableAmount
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setReceivableamount(Double receivableamount) {
        this.receivableamount = receivableamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_account_payable.discountAmount
     *
     * @return the value of financial_management_account_payable.discountAmount
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getDiscountamount() {
        return discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_account_payable.discountAmount
     *
     * @param discountamount the value for financial_management_account_payable.discountAmount
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setDiscountamount(Double discountamount) {
        this.discountamount = discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_account_payable.actualAmount
     *
     * @return the value of financial_management_account_payable.actualAmount
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getActualamount() {
        return actualamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_account_payable.actualAmount
     *
     * @param actualamount the value for financial_management_account_payable.actualAmount
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setActualamount(Double actualamount) {
        this.actualamount = actualamount;
    }
}