package cn.clothes.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="financial_management_payroll")
public class FinancialManagementPayroll {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_payroll.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_payroll.financialManagementPayrollID
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer financialmanagementpayrollid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_payroll.employeeNumber
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer employeenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_payroll.station
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String station;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_payroll.basicWage
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double basicwage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_payroll.overtimePay
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double overtimepay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_payroll.boardWages
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double boardwages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_payroll.wageDeduction
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double wagededuction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_payroll.realWages
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double realwages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management_payroll.month
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String month;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_payroll.id
     *
     * @return the value of financial_management_payroll.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Id
	@GeneratedValue
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_payroll.id
     *
     * @param id the value for financial_management_payroll.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_payroll.financialManagementPayrollID
     *
     * @return the value of financial_management_payroll.financialManagementPayrollID
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Integer getFinancialmanagementpayrollid() {
        return financialmanagementpayrollid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_payroll.financialManagementPayrollID
     *
     * @param financialmanagementpayrollid the value for financial_management_payroll.financialManagementPayrollID
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setFinancialmanagementpayrollid(Integer financialmanagementpayrollid) {
        this.financialmanagementpayrollid = financialmanagementpayrollid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_payroll.employeeNumber
     *
     * @return the value of financial_management_payroll.employeeNumber
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Integer getEmployeenumber() {
        return employeenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_payroll.employeeNumber
     *
     * @param employeenumber the value for financial_management_payroll.employeeNumber
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setEmployeenumber(Integer employeenumber) {
        this.employeenumber = employeenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_payroll.station
     *
     * @return the value of financial_management_payroll.station
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_payroll.station
     *
     * @param station the value for financial_management_payroll.station
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setStation(String station) {
        this.station = station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_payroll.basicWage
     *
     * @return the value of financial_management_payroll.basicWage
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getBasicwage() {
        return basicwage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_payroll.basicWage
     *
     * @param basicwage the value for financial_management_payroll.basicWage
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setBasicwage(Double basicwage) {
        this.basicwage = basicwage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_payroll.overtimePay
     *
     * @return the value of financial_management_payroll.overtimePay
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getOvertimepay() {
        return overtimepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_payroll.overtimePay
     *
     * @param overtimepay the value for financial_management_payroll.overtimePay
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setOvertimepay(Double overtimepay) {
        this.overtimepay = overtimepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_payroll.boardWages
     *
     * @return the value of financial_management_payroll.boardWages
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getBoardwages() {
        return boardwages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_payroll.boardWages
     *
     * @param boardwages the value for financial_management_payroll.boardWages
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setBoardwages(Double boardwages) {
        this.boardwages = boardwages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_payroll.wageDeduction
     *
     * @return the value of financial_management_payroll.wageDeduction
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getWagededuction() {
        return wagededuction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_payroll.wageDeduction
     *
     * @param wagededuction the value for financial_management_payroll.wageDeduction
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setWagededuction(Double wagededuction) {
        this.wagededuction = wagededuction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_payroll.realWages
     *
     * @return the value of financial_management_payroll.realWages
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getRealwages() {
        return realwages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_payroll.realWages
     *
     * @param realwages the value for financial_management_payroll.realWages
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setRealwages(Double realwages) {
        this.realwages = realwages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management_payroll.month
     *
     * @return the value of financial_management_payroll.month
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management_payroll.month
     *
     * @param month the value for financial_management_payroll.month
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setMonth(String month) {
        this.month = month;
    }
}