package cn.clothes.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="ingredients_table")
public class IngredientsTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ingredients_table.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ingredients_table.ingredientsNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer ingredientsno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ingredients_table.typesOfAttachment
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String typesofattachment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ingredients_table.id
     *
     * @return the value of ingredients_table.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Id
	@GeneratedValue
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ingredients_table.id
     *
     * @param id the value for ingredients_table.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ingredients_table.ingredientsNo
     *
     * @return the value of ingredients_table.ingredientsNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Integer getIngredientsno() {
        return ingredientsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ingredients_table.ingredientsNo
     *
     * @param ingredientsno the value for ingredients_table.ingredientsNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setIngredientsno(Integer ingredientsno) {
        this.ingredientsno = ingredientsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ingredients_table.typesOfAttachment
     *
     * @return the value of ingredients_table.typesOfAttachment
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getTypesofattachment() {
        return typesofattachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ingredients_table.typesOfAttachment
     *
     * @param typesofattachment the value for ingredients_table.typesOfAttachment
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setTypesofattachment(String typesofattachment) {
        this.typesofattachment = typesofattachment;
    }
}