package cn.clothes.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="lining_table")
public class LiningTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lining_table.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lining_table.fabricNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer fabricno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lining_table.fabricTypes
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String fabrictypes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lining_table.id
     *
     * @return the value of lining_table.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Id
	@GeneratedValue
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lining_table.id
     *
     * @param id the value for lining_table.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lining_table.fabricNo
     *
     * @return the value of lining_table.fabricNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Integer getFabricno() {
        return fabricno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lining_table.fabricNo
     *
     * @param fabricno the value for lining_table.fabricNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setFabricno(Integer fabricno) {
        this.fabricno = fabricno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lining_table.fabricTypes
     *
     * @return the value of lining_table.fabricTypes
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getFabrictypes() {
        return fabrictypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lining_table.fabricTypes
     *
     * @param fabrictypes the value for lining_table.fabricTypes
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setFabrictypes(String fabrictypes) {
        this.fabrictypes = fabrictypes;
    }
}