package cn.clothes.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="production_record_status_table")
public class ProductionRecordStatusTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_record_status_table.StatusNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer statusno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_record_status_table.Status
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_record_status_table.StatusNo
     *
     * @return the value of production_record_status_table.StatusNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Integer getStatusno() {
        return statusno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_record_status_table.StatusNo
     *
     * @param statusno the value for production_record_status_table.StatusNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setStatusno(Integer statusno) {
        this.statusno = statusno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_record_status_table.Status
     *
     * @return the value of production_record_status_table.Status
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_record_status_table.Status
     *
     * @param status the value for production_record_status_table.Status
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}