package cn.clothes.domain;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name="production_plan")
public class ProductionPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_plan.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_plan.productQuantity
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer productquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_plan.qualityOfProducts
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String qualityofproducts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_plan.cost
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_plan.deliveryDate
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Date deliverydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_plan.id
     *
     * @return the value of production_plan.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Id
	@GeneratedValue
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_plan.id
     *
     * @param id the value for production_plan.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_plan.productQuantity
     *
     * @return the value of production_plan.productQuantity
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Integer getProductquantity() {
        return productquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_plan.productQuantity
     *
     * @param productquantity the value for production_plan.productQuantity
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setProductquantity(Integer productquantity) {
        this.productquantity = productquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_plan.qualityOfProducts
     *
     * @return the value of production_plan.qualityOfProducts
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getQualityofproducts() {
        return qualityofproducts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_plan.qualityOfProducts
     *
     * @param qualityofproducts the value for production_plan.qualityOfProducts
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setQualityofproducts(String qualityofproducts) {
        this.qualityofproducts = qualityofproducts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_plan.cost
     *
     * @return the value of production_plan.cost
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_plan.cost
     *
     * @param cost the value for production_plan.cost
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_plan.deliveryDate
     *
     * @return the value of production_plan.deliveryDate
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Date getDeliverydate() {
        return deliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_plan.deliveryDate
     *
     * @param deliverydate the value for production_plan.deliveryDate
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }
}