package cn.clothes.domain;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="product_management_function_table")
public class ProductManagementFunctionTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_management_function_table.featureNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer featureno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_management_function_table.feature
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String feature;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_management_function_table.featureNo
     *
     * @return the value of product_management_function_table.featureNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Id
    public Integer getFeatureno() {
        return featureno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_management_function_table.featureNo
     *
     * @param featureno the value for product_management_function_table.featureNo
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setFeatureno(Integer featureno) {
        this.featureno = featureno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_management_function_table.feature
     *
     * @return the value of product_management_function_table.feature
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_management_function_table.feature
     *
     * @param feature the value for product_management_function_table.feature
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setFeature(String feature) {
        this.feature = feature;
    }
}