package cn.clothes.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="quality_monitor")
public class QualityMonitor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality_monitor.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality_monitor.fabric
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String fabric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality_monitor.excipients
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String excipients;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality_monitor.style
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality_monitor.color
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality_monitor.size
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality_monitor.workmanship
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Byte workmanship;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality_monitor.id
     *
     * @return the value of quality_monitor.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Id
	@GeneratedValue
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality_monitor.id
     *
     * @param id the value for quality_monitor.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality_monitor.fabric
     *
     * @return the value of quality_monitor.fabric
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getFabric() {
        return fabric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality_monitor.fabric
     *
     * @param fabric the value for quality_monitor.fabric
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setFabric(String fabric) {
        this.fabric = fabric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality_monitor.excipients
     *
     * @return the value of quality_monitor.excipients
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getExcipients() {
        return excipients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality_monitor.excipients
     *
     * @param excipients the value for quality_monitor.excipients
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setExcipients(String excipients) {
        this.excipients = excipients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality_monitor.style
     *
     * @return the value of quality_monitor.style
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality_monitor.style
     *
     * @param style the value for quality_monitor.style
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setStyle(String style) {
        this.style = style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality_monitor.color
     *
     * @return the value of quality_monitor.color
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality_monitor.color
     *
     * @param color the value for quality_monitor.color
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality_monitor.size
     *
     * @return the value of quality_monitor.size
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality_monitor.size
     *
     * @param size the value for quality_monitor.size
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality_monitor.workmanship
     *
     * @return the value of quality_monitor.workmanship
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Byte getWorkmanship() {
        return workmanship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality_monitor.workmanship
     *
     * @param workmanship the value for quality_monitor.workmanship
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setWorkmanship(Byte workmanship) {
        this.workmanship = workmanship;
    }
}