package cn.clothes.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="research")
public class Research {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.name
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.specification
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String specification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.shoulder
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double shoulder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.breast
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double breast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.chestCircumference
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double chestcircumference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.waistline
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double waistline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.fishtailing
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double fishtailing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.sleeveLength
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double sleevelength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.fabric
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String fabric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.ingredients
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String ingredients;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.responsibleDepartment
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String responsibledepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.productQuotation
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double productquotation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column research.sampleCostAccounting
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Double samplecostaccounting;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.id
     *
     * @return the value of research.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Id
	@GeneratedValue
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.id
     *
     * @param id the value for research.id
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.name
     *
     * @return the value of research.name
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.name
     *
     * @param name the value for research.name
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.specification
     *
     * @return the value of research.specification
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.specification
     *
     * @param specification the value for research.specification
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setSpecification(String specification) {
        this.specification = specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.shoulder
     *
     * @return the value of research.shoulder
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getShoulder() {
        return shoulder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.shoulder
     *
     * @param shoulder the value for research.shoulder
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setShoulder(Double shoulder) {
        this.shoulder = shoulder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.breast
     *
     * @return the value of research.breast
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getBreast() {
        return breast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.breast
     *
     * @param breast the value for research.breast
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setBreast(Double breast) {
        this.breast = breast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.chestCircumference
     *
     * @return the value of research.chestCircumference
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getChestcircumference() {
        return chestcircumference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.chestCircumference
     *
     * @param chestcircumference the value for research.chestCircumference
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setChestcircumference(Double chestcircumference) {
        this.chestcircumference = chestcircumference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.waistline
     *
     * @return the value of research.waistline
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getWaistline() {
        return waistline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.waistline
     *
     * @param waistline the value for research.waistline
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setWaistline(Double waistline) {
        this.waistline = waistline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.fishtailing
     *
     * @return the value of research.fishtailing
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getFishtailing() {
        return fishtailing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.fishtailing
     *
     * @param fishtailing the value for research.fishtailing
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setFishtailing(Double fishtailing) {
        this.fishtailing = fishtailing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.sleeveLength
     *
     * @return the value of research.sleeveLength
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getSleevelength() {
        return sleevelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.sleeveLength
     *
     * @param sleevelength the value for research.sleeveLength
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setSleevelength(Double sleevelength) {
        this.sleevelength = sleevelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.fabric
     *
     * @return the value of research.fabric
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getFabric() {
        return fabric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.fabric
     *
     * @param fabric the value for research.fabric
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setFabric(String fabric) {
        this.fabric = fabric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.ingredients
     *
     * @return the value of research.ingredients
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getIngredients() {
        return ingredients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.ingredients
     *
     * @param ingredients the value for research.ingredients
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setIngredients(String ingredients) {
        this.ingredients = ingredients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.responsibleDepartment
     *
     * @return the value of research.responsibleDepartment
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getResponsibledepartment() {
        return responsibledepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.responsibleDepartment
     *
     * @param responsibledepartment the value for research.responsibleDepartment
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setResponsibledepartment(String responsibledepartment) {
        this.responsibledepartment = responsibledepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.productQuotation
     *
     * @return the value of research.productQuotation
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getProductquotation() {
        return productquotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.productQuotation
     *
     * @param productquotation the value for research.productQuotation
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setProductquotation(Double productquotation) {
        this.productquotation = productquotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column research.sampleCostAccounting
     *
     * @return the value of research.sampleCostAccounting
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public Double getSamplecostaccounting() {
        return samplecostaccounting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column research.sampleCostAccounting
     *
     * @param samplecostaccounting the value for research.sampleCostAccounting
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setSamplecostaccounting(Double samplecostaccounting) {
        this.samplecostaccounting = samplecostaccounting;
    }
}