package cn.clothes.domain;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="user_right")
public class UserRight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_right.userNum
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private Integer usernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_right.userType
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    private String usertype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_right.userNum
     *
     * @return the value of user_right.userNum
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    @Id
    public Integer getUsernum() {
        return usernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_right.userNum
     *
     * @param usernum the value for user_right.userNum
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setUsernum(Integer usernum) {
        this.usernum = usernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_right.userType
     *
     * @return the value of user_right.userType
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_right.userType
     *
     * @param usertype the value for user_right.userType
     *
     * @mbg.generated Fri Mar 16 14:27:05 CST 2018
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }
}