package cn.clothes.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="user_table")
public class UserTable {
	private Integer id;
	@Id
	@GeneratedValue
    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userName
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
	private String identitycard;
	public String getIdentitycard() {
		return identitycard;
	}

	public void setIdentitycard(String identitycard) {
		this.identitycard = identitycard;
	}

	private Integer permissionnum;
    public Integer getPermissionnum() {
		return permissionnum;
	}

	public void setPermissionnum(Integer permissionnum) {
		this.permissionnum = permissionnum;
	}

	private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.password
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.age
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    private Integer age;
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.address
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.sex
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    private String sex;

  
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userName
     *
     * @param username the value for user_table.userName
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.password
     *
     * @return the value of user_table.password
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.password
     *
     * @param password the value for user_table.password
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.age
     *
     * @return the value of user_table.age
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.age
     *
     * @param age the value for user_table.age
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.contact
     *
     * @param contact the value for user_table.contact
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.address
     *
     * @return the value of user_table.address
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.address
     *
     * @param address the value for user_table.address
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.sex
     *
     * @return the value of user_table.sex
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.sex
     *
     * @param sex the value for user_table.sex
     *
     * @mbg.generated Mon Mar 12 21:25:51 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

}